- name: Prepare
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Create existing KV1 secret engine to be replaced
      trippsc2.hashi_vault.vault_kv1_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_kv1_1
        state: present

    - name: Create existing KV1 secret engine to test error
      trippsc2.hashi_vault.vault_kv1_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_kv1_2
        state: present

    - name: Create existing PKI secret engine to be removed
      trippsc2.hashi_vault.vault_pki_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_pki
        state: present
