---
- name: Verify
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Attempt to create PKI secret engine over existing KV1 secret engine
      trippsc2.hashi_vault.vault_pki_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_kv1_2
        state: present
      register: _result
      ignore_errors: true
    
    - name: Verify that the PKI secret engine failed to create
      ansible.builtin.assert:
        that:
          - _result is failed
        fail_msg: The PKI secret engine was created, but it should have failed.
        success_msg: The PKI secret engine failed to create as expected.
