---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create PKI Intermediate CA Certificate CSR
      trippsc2.hashi_vault.vault_pki_generate_intermediate_csr:
        engine_mount_point: pki
        common_name: Intermediate CA
        type: internal
        alt_names:
          - test1.test.loc
          - test2.test.loc
        ip_sans:
          - '192.0.2.1'
          - '192.0.2.2'
        uri_sans:
          - 'http://test1.test.loc'
          - 'http://test2.test.loc'
        other_sans:
          - oid: '1.3.6.1.4.1.311.20.2.3'
            value: test1@test.loc
          - oid: '1.3.6.1.4.1.311.20.2.3'
            value: test2@test.loc
        format: pem_bundle
        private_key_format: der
        key_type: rsa
        key_bits: 4096
        exclude_cn_from_sans: true
        ou:
          - Test
          - Test2
        organization:
          - Test
          - Test2
        country:
          - US
          - CA
        locality:
          - Los Angeles
          - Toronto
        province:
          - California
          - Ontario
        street_address:
          - '1234 Test St'
          - '5678 Test St'
        postal_code:
          - '90001'
          - 'M1A 1A1'
        serial_number: '1'
        add_basic_constraints: true
        key_usage:
          - DigitalSignature
          - CertSign
          - CRLSign
      register: _pki_root_ca_certificate

    - name: Write CSR to file
      ansible.builtin.copy:
        content: "{{ _pki_root_ca_certificate.csr }}"
        dest: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/pki_intermediate_ca.csr"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0600'

    - name: Create PKI Intermediate CA Certificate CSR with existing private key
      trippsc2.hashi_vault.vault_pki_generate_intermediate_csr:
        engine_mount_point: pki
        common_name: IntermediateCA
        type: existing
        key_ref: "{{ _pki_root_ca_certificate.key_id }}"
        alt_names:
          - test1.test.loc
          - test2.test.loc
        ip_sans:
          - '192.0.2.1'
          - '192.0.2.2'
        uri_sans:
          - 'http://test1.test.loc'
          - 'http://test2.test.loc'
        other_sans:
          - oid: '1.3.6.1.4.1.311.20.2.3'
            value: test1@test.loc
          - oid: '1.3.6.1.4.1.311.20.2.3'
            value: test2@test.loc
        format: pem_bundle
        private_key_format: der
        exclude_cn_from_sans: false
        ou:
          - Test
          - Test2
        organization:
          - Test
          - Test2
        country:
          - US
          - CA
        locality:
          - Los Angeles
          - Toronto
        province:
          - California
          - Ontario
        street_address:
          - '1234 Test St'
          - '5678 Test St'
        postal_code:
          - '90001'
          - 'M1A 1A1'
        serial_number: '2'
        add_basic_constraints: true
      register: _pki_root_ca_certificate

    - name: Write CSR to file
      ansible.builtin.copy:
        content: "{{ _pki_root_ca_certificate.csr }}"
        dest: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/pki_intermediate_ca_existing_key.csr"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0600'
