---
- name: Generate CSR and sign certificate
  when:
    - cert_csr_content | default('') != ''
  block:
    - name: Sign certificate with Hashicorp Vault
      delegate_to: localhost
      trippsc2.hashi_vault.vault_pki_sign_verbatim:
        token: "{{ vault_token | default(omit) }}"
        url: "{{ vault_url | default(omit) }}"
        engine_mount_point: "{{ cert_vault_mount_point }}"
        role_name: "{{ cert_vault_role }}"
        csr: "{{ cert_csr_content }}"
      register: _cert_data

    - name: Set certificate content
      when:
        - cert_certificate_to_variable
      ansible.builtin.set_fact:
        cert_certificate_content: "{{ _cert_data.certificate }}"

    - name: Copy certificate to path
      when:
        - cert_certificate_to_file
      ansible.windows.win_copy:
        content: "{{ _cert_data.certificate }}"
        dest: "{{ cert_certificate_path }}"

    - name: Copy the CA chain to the expected path
      when:
        - cert_copy_ca_chain
      block:
        - name: Format CA certificate chain
          ansible.builtin.set_fact:
            _ca_chain: "{{ _cert_data.ca_chain | join('\n') }}"

        - name: Copy the CA chain to the expected path
          ansible.windows.win_copy:
            content: "{{ _ca_chain }}"
            dest: "{{ cert_ca_chain_path }}"

    - name: Clear CSR content
      ansible.builtin.set_fact:
        cert_csr_content: ''
