---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create OpenSSH key pair
      community.crypto.openssh_keypair:
        path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/id_rsa"
        type: rsa
        size: 2048
        state: present
      register: _openssh_keypair

    - name: Sign host certificate
      trippsc2.hashi_vault.vault_ssh_sign_public_key:
        engine_mount_point: ssh
        name: host_ca
        public_key: "{{ _openssh_keypair.public_key }}"
        cert_type: host
        valid_principals:
          - host.example.com
      register: _signed_host_certificate

    - name: Sign user certificate
      trippsc2.hashi_vault.vault_ssh_sign_public_key:
        engine_mount_point: ssh
        name: user_ca
        public_key: "{{ _openssh_keypair.public_key }}"
        cert_type: user
        valid_principals:
          - user@example.com
      register: _signed_user_certificate
