- name: Prepare
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create SSH secret engine
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: ssh
        state: present

    - name: Generate SSH CA signing key
      trippsc2.hashi_vault.vault_ssh_ca_signing_key:
        engine_mount_point: ssh
        state: present

    - name: Create SSH host CA Role
      trippsc2.hashi_vault.vault_ssh_ca_role:
        engine_mount_point: ssh
        name: host_ca
        allow_host_certificates: true
        allowed_domains:
          - 'example.com'
          - 'localdomain'
        allow_bare_domains: true
        allow_subdomains: true
        state: present

    - name: Create SSH user CA Role
      trippsc2.hashi_vault.vault_ssh_ca_role:
        engine_mount_point: ssh
        name: user_ca
        allow_user_certificates: true
        allowed_users:
          - '*'
        allowed_users_template: true
        state: present
