---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: vault
    box: jtarpley/rocky9_cis
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_signed_certificate_win_pipe_
  - name: win
    box: jtarpley/${MOLECULE_BOX:-w2025_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_signed_certificate_win_pipe_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['vault'].ansible_host }}:8200"
      subjects:
        _cert_certificate_path: C:\Windows\Temp\cert.crt
        _cert_private_key_path: C:\Windows\Temp\cert.key
        cert_private_key_to_file: false
        cert_private_key_to_variable: true
        cert_certificate_to_file: false
        cert_certificate_to_variable: true
        cert_existing_certificate_type: pipe
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
    host_vars:
      win:
        ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o StrictHostKeyChecking=no'
verifier:
  name: ansible
