---
argument_specs:
  main:
    short_description: Create Testing Hashicorp Vault
    description:
      - This role configures Hashicorp Vault in development mode for use in Molecule testing.
    author: Jim Tarpley (@trippsc2)
    options:
      vault_token:
        type: str
        required: true
        description:
          - The token to use for authenticating to Vault.
      vault_listen_address:
        type: str
        required: false
        default: "{{ vault_ip_address }}"
        description:
          - The address on which Vault will listen.
      vault_listen_port:
        type: int
        required: false
        default: 8200
        description:
          - The port on which Vault will listen.
      vault_configure_firewalld:
        type: bool
        required: false
        description:
          - Whether to configure firewalld.
          - For EL and Debian systems, this will default to true.
          - For Ubuntu systems, this will default to false.
      vault_configure_ufw:
        type: bool
        required: false
        description:
          - Whether to configure ufw.
          - For Ubuntu systems, this will default to true.
          - For EL and Debian systems, this will default to false.
      vault_ip_address:
        type: str
        required: false
        default: "{{ ansible_host }}"
        description:
          - The IP address of the host on which Vault is running.
