---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: testing
  description: This role configures Hashicorp Vault in development mode for use in Molecule testing.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
  - name: Debian
    versions:
      - bullseye
      - bookworm
  - name: EL
    versions:
      - '8'
      - '9'
  - name: Ubuntu
    versions:
      - focal
      - jammy
      - noble

collections:
  - ansible.posix

dependencies: []
