---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_testing_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
verifier:
  name: ansible
