---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create SSH secret engine
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: test_1
        state: present

    - name: Modify SSH secret engine
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: test_1
        state: present
        default_lease_ttl: 1h
        max_lease_ttl: 24h
        description: "This is a test SSH secret engine"
        audit_non_hmac_request_keys:
          - foo
          - bar
        audit_non_hmac_response_keys:
          - foo
          - bar
        listing_visibility: hidden
        passthrough_request_headers:
          - foo
          - bar

    - name: Create SSH secret engine with arguments
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: test_2
        state: present
        default_lease_ttl: 1h
        max_lease_ttl: 24h
        description: "This is a test SSH secret engine"
        audit_non_hmac_request_keys:
          - foo
          - bar
        audit_non_hmac_response_keys:
          - foo
          - bar
        listing_visibility: hidden
        passthrough_request_headers:
          - foo
          - bar

    - name: Remove SSH secret engine
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: existing_ssh
        state: absent

    - name: Replace KV1 secret engine with SSH secret engine
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: existing_kv1_1
        replace_different_backend_type: true
