---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Check if role needs creation
      check_mode: true
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test1
        db_name: postgres
        db_username: test1

    - name: Create role
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test1
        db_name: postgres
        db_username: test1

    - name: Check if role needs modification
      check_mode: true
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test2
        db_name: postgres
        db_username: test2
        rotation_statements:
          - "ALTER ROLE \"{{ '{{username}}' }}\" SET password TO '{{ '{{password}}' }}';"
        rotation_period: 1h

    - name: Modify role
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test2
        db_name: postgres
        db_username: test2
        rotation_statements:
          - "ALTER ROLE \"{{ '{{username}}' }}\" SET password TO '{{ '{{password}}' }}';"
        rotation_period: 1h

    - name: Check if role needs deletion
      check_mode: true
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test3
        state: absent

    - name: Remove role
      trippsc2.hashi_vault.vault_database_static_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: database
        name: postgres_test3
        state: absent
