---
driver:
  name: docker
platforms:
  - name: vault
    image: docker.io/hashicorp/vault:latest
    capabilities:
      - SYS_ADMIN
      - IPC_LOCK
    exposed_ports:
      - 8200/tcp
      - 8200/udp
      - 8300/tcp
      - 8300/udp
    published_ports:
      - 0.0.0.0:8200:8200/tcp
      - 0.0.0.0:8200:8200/udp
      - 0.0.0.0:8300:8300/tcp
      - 0.0.0.0:8300:8300/udp
    command: server -dev -dev-root-token-id=47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
  - name: postgres
    image: docker.io/postgres:latest
    shm_size: 128M
    capabilities:
      - SYS_ADMIN
      - IPC_LOCK
    exposed_ports:
      - 5432/tcp
    published_ports:
      - 0.0.0.0:5432:5432/tcp
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    command: postgres
