---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Check if PKI Role is created
      check_mode: true
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: test1
        state: present

    - name: Create PKI Role
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: test1
        state: present

    - name: Check if PKI Role needs modification
      check_mode: true
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: test1
        state: present
        ttl: 30d
        max_ttl: 60d
        allow_localhost: false
        allowed_domains:
          - test.loc
        allowed_domains_template: true
        allow_bare_domains: true
        allow_subdomains: true
        allow_glob_domains: true
        allow_wildcard_certificates: false
        allow_any_name: true
        allow_ip_sans: false
        allowed_uri_sans:
          - http://test.loc
        allowed_uri_sans_template: true
        allowed_other_sans:
          - '*'
        server_flag: false
        client_flag: false
        code_signing_flag: true
        email_protection_flag: true
        key_type: rsa
        key_bits: 4096
        signature_bits: 512
        use_pss: true
        key_usage:
          - DigitalSignature
          - KeyEncipherment
        ext_key_usage:
          - ServerAuth
          - ClientAuth
        ext_key_usage_oids:
          - '1.3.6.1.5.5.7.3.9'
        use_csr_common_name: false
        use_csr_sans: false
        ou:
          - Test
          - Test2
        organization:
          - Test
          - Test2
        country:
          - US
          - CA
        locality:
          - Test
          - Test2
        province:
          - Test
          - Test2
        street_address:
          - Test
          - Test2
        postal_code:
          - Test
          - Test2
        generate_lease: false
        no_store: true
        require_cn: false
        basic_constraints_valid_for_non_ca: true
        not_before_duration: 1h
        allowed_user_ids:
          - '*'

    - name: Modify PKI Role with custom options
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: test1
        state: present
        ttl: 30d
        max_ttl: 60d
        allow_localhost: false
        allowed_domains:
          - test.loc
        allowed_domains_template: true
        allow_bare_domains: true
        allow_subdomains: true
        allow_glob_domains: true
        allow_wildcard_certificates: false
        allow_any_name: true
        allow_ip_sans: false
        allowed_uri_sans:
          - http://test.loc
        allowed_uri_sans_template: true
        allowed_other_sans:
          - '*'
        server_flag: false
        client_flag: false
        code_signing_flag: true
        email_protection_flag: true
        key_type: rsa
        key_bits: 4096
        signature_bits: 512
        use_pss: true
        key_usage:
          - DigitalSignature
          - KeyEncipherment
        ext_key_usage:
          - ServerAuth
          - ClientAuth
        ext_key_usage_oids:
          - '1.3.6.1.5.5.7.3.9'
        use_csr_common_name: false
        use_csr_sans: false
        ou:
          - Test
          - Test2
        organization:
          - Test
          - Test2
        country:
          - US
          - CA
        locality:
          - Test
          - Test2
        province:
          - Test
          - Test2
        street_address:
          - Test
          - Test2
        postal_code:
          - Test
          - Test2
        generate_lease: false
        no_store: true
        require_cn: false
        basic_constraints_valid_for_non_ca: true
        not_before_duration: 1h
        allowed_user_ids:
          - '*'

    - name: Create PKI Role with custom options
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: test2
        state: present
        ttl: 30d
        max_ttl: 60d
        allow_localhost: false
        allowed_domains:
          - test.loc
        allowed_domains_template: true
        allow_bare_domains: true
        allow_subdomains: true
        allow_glob_domains: true
        allow_wildcard_certificates: false
        allow_any_name: true
        allow_ip_sans: false
        allowed_uri_sans:
          - http://test.loc
        allowed_uri_sans_template: true
        allowed_other_sans:
          - '*'
        server_flag: false
        client_flag: false
        code_signing_flag: true
        email_protection_flag: true
        key_type: rsa
        key_bits: 4096
        signature_bits: 512
        use_pss: true
        key_usage:
          - DigitalSignature
          - KeyEncipherment
        ext_key_usage:
          - ServerAuth
          - ClientAuth
        ext_key_usage_oids:
          - '1.3.6.1.5.5.7.3.9'
        use_csr_common_name: false
        use_csr_sans: false
        ou:
          - Test
          - Test2
        organization:
          - Test
          - Test2
        country:
          - US
          - CA
        locality:
          - Test
          - Test2
        province:
          - Test
          - Test2
        street_address:
          - Test
          - Test2
        postal_code:
          - Test
          - Test2
        generate_lease: true
        no_store: false
        require_cn: false
        basic_constraints_valid_for_non_ca: true
        not_before_duration: 1h
        allowed_user_ids:
          - '*'

    - name: Check if PKI Role needed to be removed
      check_mode: true
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: ToBeDeleted
        state: absent

    - name: Remove PKI Role
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: ToBeDeleted
        state: absent
