- name: Prepare
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Create PKI secret engine
      trippsc2.hashi_vault.vault_pki_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: pki
        max_lease_ttl: 157680000
        state: present

    - name: Create PKI Role to be deleted
      trippsc2.hashi_vault.vault_pki_role:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: pki
        name: ToBeDeleted
        state: present
