- name: Prepare
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create PKI secret engine
      trippsc2.hashi_vault.vault_pki_secret_engine:
        engine_mount_point: pki
        max_lease_ttl: 157680000
        state: present
    
    - name: Generate Root CA Certificate
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        engine_mount_point: pki
        common_name: RootCA
        ttl: 157680000
        state: present

    - name: Create PKI Role
      trippsc2.hashi_vault.vault_pki_role:
        engine_mount_point: pki
        name: verbatim
        state: present
        allow_any_name: true
        allow_bare_domains: true
        allow_glob_domains: true
        allow_ip_sans: true
        allow_localhost: true
        client_flag: true
        enforce_hostnames: true
        require_cn: true
        server_flag: true
