---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_signed_certificate_linux_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['linux'].ansible_host }}:8200"
      subjects:
        cert_private_key_path: >-
          {{ '/etc/pki/tls/private/cert.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/cert.key' }}
        cert_private_key_owner: test
        cert_private_key_group: test
        cert_certificate_path: >-
          {{ '/etc/pki/tls/certs/cert.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/cert.crt' }}
        cert_certificate_owner: test
        cert_certificate_group: test
        cert_ca_chain_owner: test
        cert_ca_chain_group: test
        cert_copy_ca_chain: true
verifier:
  name: ansible
