---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: testing_ca
  description: This role configures Hashicorp Vault in development mode for use in Molecule testing as a Certification Authority.
  license: MIT

  min_ansible_version: '2.15'

  platforms:
  - name: Debian
    versions:
      - bullseye
      - bookworm
  - name: EL
    versions:
      - '8'
      - '9'
  - name: Ubuntu
    versions:
      - focal
      - jammy
      - noble

collections:
  - ansible.posix

dependencies:
  - role: trippsc2.hashi_vault.testing
