---
- name: Update CA trust (Debian-based)
  listen: _cert_update_ca_trust
  when:
    - ansible_os_family == 'Debian'
    - cert_update_ca_trust
  become: true
  ansible.builtin.command: update-ca-certificates
  changed_when: true

- name: Update CA trust (EL)
  listen: _cert_update_ca_trust
  when:
    - ansible_os_family == 'RedHat'
    - cert_update_ca_trust
  become: true
  ansible.builtin.command: update-ca-trust
  changed_when: true
