---
- name: Converge
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Create Database secret engine
      trippsc2.hashi_vault.vault_database_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: test_1
        state: present

    - name: Modify Database secret engine
      trippsc2.hashi_vault.vault_database_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: test_1
        state: present
        default_lease_ttl: 1h
        max_lease_ttl: 24h
        description: "This is a test Database secret engine"
        audit_non_hmac_request_keys:
          - foo
          - bar
        audit_non_hmac_response_keys:
          - foo
          - bar
        listing_visibility: hidden
        passthrough_request_headers:
          - foo
          - bar

    - name: Create Database secret engine with arguments
      trippsc2.hashi_vault.vault_database_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: test_2
        state: present
        default_lease_ttl: 1h
        max_lease_ttl: 24h
        description: "This is a test Database secret engine"
        audit_non_hmac_request_keys:
          - foo
          - bar
        audit_non_hmac_response_keys:
          - foo
          - bar
        listing_visibility: hidden
        passthrough_request_headers:
          - foo
          - bar

    - name: Remove Database secret engine
      trippsc2.hashi_vault.vault_database_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_database
        state: absent

    - name: Replace KV1 secret engine with Database secret engine
      trippsc2.hashi_vault.vault_database_secret_engine:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: existing_kv1_1
        replace_different_backend_type: true
