---
- name: Verify
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: Check if PKI Root CA Certificate is created
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: pki1
        common_name: RootCA
        state: present
      register: _result

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _result.changed
        fail_msg: PKI Root CA Certificate was not created
        success_msg: PKI Root CA Certificate was created

    - name: Check if PKI Root CA Certificate is created
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: pki2
        common_name: RootCA
        state: present
      register: _result

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _result.changed
        fail_msg: PKI Root CA Certificate was not created
        success_msg: PKI Root CA Certificate was created

    - name: Check if PKI Root CA Certificate is removed
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        url: http://127.0.0.1:8200
        engine_mount_point: pki3
        state: absent
      register: _result

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _result.changed
        fail_msg: PKI Root CA Certificate was not removed
        success_msg: PKI Root CA Certificate was removed
