---
- name: Verify
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Check if PKI Root CA Certificate is created
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        engine_mount_point: pki1
        common_name: RootCA
        state: present
      register: _result

    - name: Verify that PKI Root CA Certificate would not be created
      ansible.builtin.assert:
        that:
          - _result is not changed
        fail_msg: PKI Root CA Certificate would be created, but it should not be.
        success_msg: PKI Root CA Certificate would not be created as expected.

    - name: Check if PKI Root CA Certificate is created
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        engine_mount_point: pki2
        common_name: RootCA
        state: present
      register: _result

    - name: Verify that PKI Root CA Certificate would not be created
      ansible.builtin.assert:
        that:
          - _result is not changed
        fail_msg: PKI Root CA Certificate would be created, but it should not be.
        success_msg: PKI Root CA Certificate would not be created as expected.

    - name: Check if PKI Root CA Certificate is removed
      check_mode: true
      trippsc2.hashi_vault.vault_pki_root_ca_certificate:
        engine_mount_point: pki3
        state: absent
      register: _result

    - name: Verify that PKI Root CA Certificate would not be removed
      ansible.builtin.assert:
        that:
          - _result is not changed
        fail_msg: PKI Root CA Certificate would be removed, but it should not be.
        success_msg: PKI Root CA Certificate would not be removed as expected.
