---
- name: Prepare CA Vault
  hosts:
    - ca
  roles:
    - role: trippsc2.hashi_vault.testing_ca

- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Create group
      become: true
      ansible.builtin.group:
        name: vault
        system: true
        state: present

    - name: Create user
      become: true
      ansible.builtin.user:
        name: vault
        group: vault
        home: /opt/vault
        create_home: true
        password: '!'
        password_lock: true
        shell: /usr/sbin/nologin
        system: true
        state: present
  roles:
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ _vault_certificate_path }}"
        cert_private_key_path: "{{ _vault_private_key_path }}"
        cert_certificate_owner: vault
        cert_certificate_group: vault
        cert_private_key_owner: vault
        cert_private_key_group: vault
        cert_common_name: "{{ inventory_hostname }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
        cert_copy_ca_chain: false
        vault_url: "{{ _ca_vault_url }}"
        vault_token: "{{ _ca_vault_token }}"
