- name: Prepare
  hosts:
    - localhost
  gather_facts: false
  module_defaults:
    group/trippsc2.hashi_vault.vault:
      token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
      url: http://127.0.0.1:8200
  tasks:
    - name: Create SSH secret engine with existing key
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: existing_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH secret engine with no existing key
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: no_existing_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH secret engine for custom size key
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: custom_size_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH secret engine for custom ECDSA key
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: custom_ecdsa_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH secret engine with existing key to remove
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: remove_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH secret engine with no existing key to remove
      trippsc2.hashi_vault.vault_ssh_secret_engine:
        engine_mount_point: no_remove_key
        max_lease_ttl: 157680000
        state: present

    - name: Create SSH CA signing key
      trippsc2.hashi_vault.vault_ssh_ca_signing_key:
        engine_mount_point: existing_key
        state: present

    - name: Create SSH CA signing key to remove
      trippsc2.hashi_vault.vault_ssh_ca_signing_key:
        engine_mount_point: remove_key
        state: present
