---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: vault
    box: jtarpley/rocky9_cis
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_signed_certificate_linux_pipe_
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: hashi_vault_signed_certificate_linux_pipe_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['vault'].ansible_host }}:8200"
      subjects:
        _cert_private_key_path: >-
          {{ '/etc/pki/tls/private/cert.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/cert.key' }}
        _cert_certificate_path: >-
          {{ '/etc/pki/tls/certs/cert.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/cert.crt' }}
        cert_private_key_to_file: false
        cert_private_key_to_variable: true
        cert_certificate_to_file: false
        cert_certificate_to_variable: true
        cert_existing_certificate_type: pipe
verifier:
  name: ansible
