---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start HashiCorp Vault
  become: true
  ansible.builtin.systemd_service:
    name: vault.service
    enabled: true
    state: started
