---
- name: Create group
  become: true
  ansible.builtin.group:
    name: "{{ vault_group }}"
    system: true
    state: present

- name: Create user
  become: true
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    home: "{{ vault_home_directory }}"
    create_home: true
    password: '!'
    password_lock: true
    shell: /usr/sbin/nologin
    system: true
    state: present
